"""Another Migration

Revision ID: 367a7389740d
Revises: fe5660a9aa15
Create Date: 2022-05-07 23:15:10.961138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367a7389740d'
down_revision = 'fe5660a9aa15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('categories', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('pitches', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('content', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('time', sa.DateTime(), nullable=True))
    op.add_column('pitches', sa.Column('category', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_pitches_category'), 'pitches', ['category'], unique=False)
    op.create_foreign_key(None, 'pitches', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    op.alter_column('users', 'pass_secure',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'pass_secure',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_index(op.f('ix_pitches_category'), table_name='pitches')
    op.drop_column('pitches', 'category')
    op.drop_column('pitches', 'time')
    op.drop_column('pitches', 'content')
    op.drop_column('pitches', 'user_id')
    op.drop_column('categories', 'description')
    op.drop_column('categories', 'name')
    # ### end Alembic commands ###
